### ISSUE TITLE
conflict with #include <ESP8266WiFi.h> 

### ISSUE THREAD

**Issue by Primus007** [earlephilhower/ESP8266SdFat#6]
i have compiled your ReadWrite example. It works fine.
Then i have added: #include <ESP8266WiFi.h>

If i compile i get some error:
                `ReadWrite:29:1: error: reference to 'File' is ambiguous`
                  
                 File myFile;

                  ^

                 In file included from C:\Users\pl\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1\libraries\ESP8266WiFi\src/CertStoreBearSSL.h:26:0,

                 from C:\Users\pl\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1\libraries\ESP8266WiFi\src/WiFiClientSecureBearSSL.h:30,

                 from C:\Users\pl\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1\libraries\ESP8266WiFi\src/WiFiClientSecure.h:41,

                 from C:\Users\pl\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1\libraries\ESP8266WiFi\src/WiFiServerSecure.h:20,

                 from C:\Users\pl\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1\libraries\ESP8266WiFi\src/ESP8266WiFi.h:41,

                 from C:\Users\pl\AppData\Local\Temp\arduino_modified_sketch_675739\ReadWrite.ino:23:

                 C:\Users\pl\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1\cores\esp8266/FS.h:52:7: note: candidates are: class fs::File

                 class File : public Stream

                 In file included from F:\Eigene Dateien\Arduino\libraries\ESP8266SdFat-master\src/FatLib/FatLib.h:27:0,

                 from F:\Eigene Dateien\Arduino\libraries\ESP8266SdFat-master\src/SdFat.h:33,

                 from C:\Users\pl\AppData\Local\Temp\arduino_modified_sketch_675739\ReadWrite.ino:22:

                  F:\Eigene Dateien\Arduino\libraries\ESP8266SdFat-master\src/FatLib/ArduinoFiles.h:125:7: note:                 class sdfat::File

                  class File : public FatFile, public Stream {

                  ReadWrite:29:1: error: 'File' does not name a type

                  File myFile;

                  C:\Users\pl\AppData\Local\Temp\arduino_modified_sketch_675739\ReadWrite.ino: In function 'void setup()':

                  ReadWrite:49:3: error: 'myFile' was not declared in this scope

                  myFile = SD.open("test.txt", FILE_WRITE);

                  exit status 1
                  reference to 'File' is ambiguous

`

Why does this not work with ESP8266WiFi.h ? I there any way to get it to work.

**Comment by earlephilhower** [comment]
Again, as has been said in other repos before, please do not use the ESP8266SDFat stuff directly.  They have a `File` which is incompatible with the Arduino `File`.  Use the `SDFS` or `SD` filesystem.
